export type Mock = {
    id: number,
    inspection: string,
    startInspectionDate: string,
    endInspectionDate: string,
    auditViolation: string,
    recommendation: string,
    status: 'open' | 'overdue' | 'closed' | 'removed',
    riskLevel: 'high' | 'medium' | 'low',
    responsibleUnit: string[],
    responsiblePerson: string[],
    scheduledDate: string,
    executionDate: string | null
}

export const mockIssues: Mock[] = [
    {
        id: 1,
        inspection: "Аудит мониторинга предметов лизинга (Автотранспорт)",
        startInspectionDate: "2026-08-10",
        endInspectionDate: "2026-08-14",
        auditViolation: "У 15 грузовых автомобилей в лизинге по договору с ООО 'Транс-Логистик' отключены или неисправны GPS-трекеры.",
        recommendation: "Направить лизингополучателю требование о восстановлении связи и провести внеплановый выездной осмотр техники.",
        status: "open",
        riskLevel: "high",
        responsibleUnit: ["Департамент мониторинга рисков", "Управление безопасности"],
        responsiblePerson: ["Иванов И.И.", "Сидоров С.С."],
        scheduledDate: "2026-09-15",
        executionDate: null
    },
    {
        id: 2,
        inspection: "Проверка страхования портфеля спецтехники (КАСКО)",
        startInspectionDate: "2026-08-17",
        endInspectionDate: "2026-08-20",
        auditViolation: "Выявлено 7 договоров лизинга экскаваторов с истекшим сроком действия полисов КАСКО.",
        recommendation: "Активировать процедуру автоматического пролонгирования страховки силами лизингодателя с выставлением счета клиентам.",
        status: "closed",
        riskLevel: "medium",
        responsibleUnit: ["Отдел страхования", "Сопровождение сделок"],
        responsiblePerson: ["Петрова А.В."],
        scheduledDate: "2026-08-25",
        executionDate: "2026-08-24"
    },
    {
        id: 3,
        inspection: "Аудит соблюдения требований ПОД/ФТ (Росфинмониторинг)",
        startInspectionDate: "2026-08-03",
        endInspectionDate: "2026-08-07",
        auditViolation: "Несвоевременная отправка отчетов об операциях обязательного контроля по сделкам возвратного лизинга.",
        recommendation: "Обновить программный модуль выгрузки в личном кабинете РФМ и провести переаттестацию сотрудников комплаенс.",
        status: "overdue",
        riskLevel: "high",
        responsibleUnit: ["Служба комплаенс-контроля"],
        responsiblePerson: ["Козлов В.П.", "Григорьев Д.А."],
        scheduledDate: "2026-08-31",
        executionDate: null
    },
    {
        id: 4,
        inspection: "Анализ работы с дебиторской задолженностью и цессии",
        startInspectionDate: "2026-08-24",
        endInspectionDate: "2026-08-28",
        auditViolation: "Задержка запуска процедуры изъятия имущества по договорам с просрочкой платежа более 90 дней.",
        recommendation: "Ускорить передачу дел в юридический департамент и инициировать досудебное изъятие предметов лизинга.",
        status: "open",
        riskLevel: "high",
        responsibleUnit: ["Отдел взыскания задолженности", "Юридический департамент"],
        responsiblePerson: ["Морозов К.Э."],
        scheduledDate: "2026-10-01",
        executionDate: null
    },
    {
        id: 5,
        inspection: "Инспекция хранения изъятого имущества на штрафстоянках",
        startInspectionDate: "2026-07-15",
        endInspectionDate: "2026-07-17",
        auditViolation: "На стоянке хранения изъятых легковых авто отсутствуют акты приема-передачи материальных ценностей подрядчиком.",
        recommendation: "Провести инвентаризацию стоянки и обязать подрядчика подписать акты под угрозой расторжения договора.",
        status: "closed",
        riskLevel: "low",
        responsibleUnit: ["Департамент изъятого имущества", "АХО"],
        responsiblePerson: ["Васильев Н.О."],
        scheduledDate: "2026-08-10",
        executionDate: "2026-08-08"
    },
    {
        id: 6,
        inspection: "Аудит процесса скоринга и одобрения лизинговых сделок",
        startInspectionDate: "2026-08-11",
        endInspectionDate: "2026-08-14",
        auditViolation: "В модуле автоматической проверки БКИ некорректно учитываются поручительства бенефициаров малого бизнеса.",
        recommendation: "Скорректировать скоринговую модель в ERP-системе для снижения доли необоснованных отказов.",
        status: "open",
        riskLevel: "medium",
        responsibleUnit: ["Управление риск-менеджмента", "IT-отдел"],
        responsiblePerson: ["Павлова Е.Д.", "Федоров А.М."],
        scheduledDate: "2026-09-20",
        executionDate: null
    },
    {
        id: 7,
        inspection: "Проверка чистоты сделок финансового лизинга недвижимости",
        startInspectionDate: "2026-09-01",
        endInspectionDate: "2026-09-03",
        auditViolation: "Отсутствие выписки из ЕГРН в юридическом досье по крупному строящемуся объекту (складской комплекс).",
        recommendation: "Запросить актуальные сведения из Росреестра и прикрепить скан-копии в карточку сделки CRM.",
        status: "open",
        riskLevel: "medium",
        responsibleUnit: ["Юридический департамент"],
        responsiblePerson: ["Смирнов Ю.Б."],
        scheduledDate: "2026-09-10",
        executionDate: null
    },
    {
        id: 8,
        inspection: "Аудит маркетинговых программ с автодилерами (Субсидии)",
        startInspectionDate: "2026-07-20",
        endInspectionDate: "2026-07-25",
        auditViolation: "Расчет скидок по совместной программе с брендом HAVAL производился по устаревшим прайс-листам.",
        recommendation: "Аннулировать ошибочные калькуляции, обновить тарифную сетку и сделать перерасчет маржинальности.",
        status: "removed",
        riskLevel: "low",
        responsibleUnit: ["Управление продаж и партнерских программ"],
        responsiblePerson: ["Тихонов И.А."],
        scheduledDate: "2026-08-15",
        executionDate: null
    },
    {
        id: 9,
        inspection: "Проверка регистрации предметов лизинга в госорганах",
        startInspectionDate: "2026-08-05",
        endInspectionDate: "2026-08-07",
        auditViolation: "Выявлено 4 полуприцепа, не поставленных лизингополучателем на временный учет в ГИБДД в течение 10 дней.",
        recommendation: "Выставить штрафные санкции согласно договору и обязать клиента предоставить СТС.",
        status: "closed",
        riskLevel: "low",
        responsibleUnit: ["Сопровождение сделок", "Группа регистрации"],
        responsiblePerson: ["Дмитриева М.В."],
        scheduledDate: "2026-08-20",
        executionDate: "2026-08-19"
    },
    {
        id: 10,
        inspection: "Аудит лизинговых сделок с государственным участием (ЛК-Субсидии Минпромторга)",
        startInspectionDate: "2026-08-12",
        endInspectionDate: "2026-08-14",
        auditViolation: "Пакет документов на получение государственной субсидии по колесной технике сформирован с нарушением требований Минпромторга.",
        recommendation: "Срочно пересобрать отчетность по льготному лизингу во избежание отказа в компенсации выпадающих доходов.",
        status: "overdue",
        riskLevel: "high",
        responsibleUnit: ["Финансово-аналитический департамент"],
        responsiblePerson: ["Яковлев С.Н.", "Кузнецов Е.В."],
        scheduledDate: "2026-09-01",
        executionDate: null
    }
]